apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: account-service:latest
          ports:
            - containerPort: 8088
            - containerPort: 8089
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=account-db;Port=5432;Username=postgres;Password=mysecretpassword;Database=accountdb"
