apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
  selector:
    app: card
  ports:
    - name: http-8086
      port: 8086
      targetPort: 8086
    - name: http-8087
      port: 8087
      targetPort: 8087
