services:

  account-db:
    image: postgres:15-alpine
    container_name: account-db
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - account-db-data:/var/lib/postgresql/data
    networks:
      - app-network
  account.dashboard:
    image : mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name : dashboard_ACCOUNT
    ports:
    - 18888:18888
    - 18889:18889
    networks:
      - app-network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
      - xpack.fleet.enabled=false         
      - xpack.fleet.agents.enabled=false  
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  account-service:
    build:
      context: .
      dockerfile: OpenBanking_ACCOUNT_V1/Dockerfile
    container_name: account-service
    ports:
      - "8088:8088"
      - "8089:8089"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=account-db;Port=5432;Username=postgres;Password=mysecretpassword;Database=accountdb
    depends_on:
      - account-db
    networks:
      - app-network

  branch-db:
    image: mysql:5.7
    container_name: branch-db
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: branchdb
    ports:
      - "3306:3306"
    volumes:
      - branch-db-data:/var/lib/mysql
    networks:
      - app-network

  branch-service:
    build:
      context: .
      dockerfile: OpenBanking_BRANCH_V1/Dockerfile
    container_name: branch-service
    ports:
      - "8084:8084"
      - "8085:8085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mysql://branch-db:3306/branchdb
    depends_on:
      - branch-db
    networks:
      - app-network

  card-db:
    image: postgres:13
    container_name: card-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: carddb
    ports:
      - "5433:5432"  
    volumes:
      - card-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  card-service:
    build:
      context: .
      dockerfile: OpenBanking_CARD_V1/Dockerfile
    container_name: card-service
    ports:
      - "8086:8086"
      - "8087:8087"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=card-db;Port=5432;Username=postgres;Password=mysecretpassword;Database=carddb
    depends_on:
      - card-db
    networks:
      - app-network

  atm-db:
    image: mongo:latest
    container_name: atm-db
    ports:
      - "27017:27017"
    networks:
      - app-network

  mysqlAuth-db:
    image: mysql:5.7
    container_name: authdb
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: authdb
    ports:
      - "3307:3306"
    volumes:
      - authdb-data:/var/lib/mysql
    networks:
      - app-network
    

  authenticator-service:
    build:
      context: .
      dockerfile: OpenBanking_AUTHENTICATOR_V1/Dockerfile
    container_name: authenticator-service
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysqlAuth-db;port=3306;database=authdb;user=root;password=mysecretpassword;SslMode=none;
    depends_on:
      - mysqlAuth-db
    user: root
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - app-network
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network
    depends_on:
      - prometheus



  frontend:
    build:
      context: ./OpenBanking_ANGULAR_V1
      dockerfile: Dockerfile
    ports:
      - "8083:80"   # Expose HTTP only
    volumes:
      - ./uploads:/shared/openBanking/uploads
    networks:
      - app-network
    restart: always



    


  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
volumes:
  account-db-data:
  branch-db-data:
  card-db-data:
  authdb-data:
  rabbitmq-lib:
  rabbitmq-log:
  esdata:
  grafana-data:
  data-protection-keys:
  
