apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'services'
        static_configs:
          - targets: ['account-service:8088', 'branch-service:8084', 'card-service:8086', 'authenticator-service:8090']
