apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbanking-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbanking
  template:
    metadata:
      labels: 
        app: openbanking
    spec:
      containers:
        - name: openbanking-account
          image: waelelgabsi/OpenBanking_ACCOUNT_V1:latest
        - name: openbanking-atm
          image: waelelgabsi/OpenBanking_ATM_V1:latest
        - name: openbanking-branch
          image: waelelgabsi/OpenBanking_BRANCH_V1:latest
        - name: openbanking-card
          image: waelelgabsi/OpenBanking_CARD_V1:latest
