apiVersion: apps/v1
kind: Deployment
metadata:
  name: Openbanking-depl-Branch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OpenBanking-Branch
  template:
    metadata:
      labels: 
        app: OpenBanking-Branch
    spec:
      containers:
        - name: openbanking-account
          image: waelelgabsi/OpenBanking_BRANCH_V1:latest

#        - name: openbanking-branch-db
#          image: waelelgabsi/mysql:5.7:latest
