apiVersion: apps/v1
kind: Deployment
metadata:
  name: Openbanking-depl-Card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OpenBanking-Card
  template:
    metadata:
      labels: 
        app: OpenBanking-Card
    spec:
      containers:
        - name: openbanking-card
          image: waelelgabsi/OpenBanking_CARD_V1:latest
        
#        - name: openbanking-card-db
#          image: waelelgabsi/postgres:13