apiVersion: apps/v1
kind: Deployment
metadata:
  name: Openbanking-depl-GRPC
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OpenBanking-GRPC
  template:
    metadata:
      labels: 
        app: OpenBanking-GRPC
    spec:
      containers:
        - name: openbanking-GRPC
          image: waelelgabsi/OpenBanking_GRPC_V1:latest
        
