apiVersion: apps/v1
kind: Deployment
metadata:
  name: Openbanking-depl-Atm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OpenBanking-Atm
  template:
    metadata:
      labels: 
        app: OpenBanking-Atm
    spec:
      containers:
        - name: openbanking-account
          image: waelelgabsi/OpenBanking_ATM_V1:latest
        
 #       - name: openbanking-atm-db
 #         image: waelelgabsi/mongo:latest