apiVersion: v1
kind: Service
metadata:
  name: authenticator-service
spec:
  selector:
    app: authenticator
  ports:
    - name: http-8090
      port: 8090
      targetPort: 8090
    - name: http-8091
      port: 8091
      targetPort: 8091
