namespace OpenBanking_ACCOUNT_V1.Models
{
    public enum AttributeType
    {
        DATE_WITH_DAY , DATE_WITH_MONTH, DATE_WITH_YEAR, DATE_WITH_TIME, DATE_WITH_TIMEZONE, TIME_WITH_HOUR, TIME_WITH_MINUTE, TIME_WITH_SECOND, TIME_WITH_MILLISECOND, TIME_WITH_MICROSECOND, TIME_WITH_NANOSECOND, TIMEZONE, TIMESTAMP_WITH_DAY, TIMESTAMP_WITH_MONTH, TIMESTAMP_WITH_YEAR, TIMESTAMP_WITH_TIME, TIMESTAMP_WITH_TIMEZONE, TIMESTAMP_WITH_HOUR, TIMESTAMP_WITH_MINUTE, TIMESTAMP_WITH_SECOND, TIMESTAMP_WITH_MILLISECOND, TIMESTAMP_WITH_MICROSECOND, TIMESTAMP_WITH_NANOSECOND
    }
}
