// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenBanking_ACCOUNT_V1.Data;

#nullable disable

namespace OpenBanking_ACCOUNT_V1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Account", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Bank_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("branch_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("number")
                        .HasColumnType("integer");

                    b.Property<string>("product_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Account_attributes", b =>
                {
                    b.Property<string>("account_attribute_id")
                        .HasColumnType("text");

                    b.Property<string>("Accountid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("product_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("product_instance_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("account_attribute_id");

                    b.HasIndex("Accountid");

                    b.ToTable("AccountAttributes");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Account_routings", b =>
                {
                    b.Property<int>("RoutingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoutingId"));

                    b.Property<string>("Accountid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Scheme")
                        .HasColumnType("integer");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoutingId");

                    b.HasIndex("Accountid");

                    b.ToTable("AccountRoutings");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Agent", b =>
                {
                    b.Property<string>("agent_id")
                        .HasColumnType("text");

                    b.Property<string>("Bank_id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_id");

                    b.Property<string>("agent_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("currency")
                        .HasColumnType("integer");

                    b.Property<bool>("is_confirmed_agent")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_pending_agent")
                        .HasColumnType("boolean");

                    b.Property<string>("legal_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mobile_phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("agent_id");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Balance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BalanceId"));

                    b.Property<string>("Accountid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<int>("currency")
                        .HasColumnType("integer");

                    b.HasKey("BalanceId");

                    b.HasIndex("Accountid");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Owners", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Accountid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dispay_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Tags", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Accountid")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.HasIndex("userid");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Views_available", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Accountid")
                        .HasColumnType("text");

                    b.Property<bool>("CanAddComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddCorporateLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddImageUrl")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddMoreInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddOpenCorporatesUrl")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddPhysicalLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddPrivateAlias")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddPublicAlias")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddTag")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddUrl")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanAddWhereTag")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteCorporateLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeletePhysicalLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteTag")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteWhereTag")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEditOwnerComment")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountBalance")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountBankName")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountCurrency")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountIban")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountLabel")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountNationalIdentifier")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountNumber")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountOwners")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountSwiftBic")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeBankAccountType")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeComments")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeCorporateLocation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeImageUrl")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeImages")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeMoreInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeOpenCorporatesUrl")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSeeOtherAccountBankName")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideMetadataIfAliasUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("alias")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_public")
                        .HasColumnType("boolean");

                    b.Property<string>("short_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Accountid");

                    b.ToTable("ViewsAvailable");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Account_attributes", b =>
                {
                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Account", "Account")
                        .WithMany("account_Attributes")
                        .HasForeignKey("Accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Account_routings", b =>
                {
                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Account", "Account")
                        .WithMany("account_routings")
                        .HasForeignKey("Accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Balance", b =>
                {
                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Account", "Account")
                        .WithMany("balances")
                        .HasForeignKey("Accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Owners", b =>
                {
                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Account", "Account")
                        .WithMany("owners")
                        .HasForeignKey("Accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Tags", b =>
                {
                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Account", null)
                        .WithMany("tags")
                        .HasForeignKey("Accountid");

                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Owners", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Views_available", b =>
                {
                    b.HasOne("OpenBanking_ACCOUNT_V1.Models.Account", null)
                        .WithMany("views_available")
                        .HasForeignKey("Accountid");
                });

            modelBuilder.Entity("OpenBanking_ACCOUNT_V1.Models.Account", b =>
                {
                    b.Navigation("account_Attributes");

                    b.Navigation("account_routings");

                    b.Navigation("balances");

                    b.Navigation("owners");

                    b.Navigation("tags");

                    b.Navigation("views_available");
                });
#pragma warning restore 612, 618
        }
    }
}
