events {}

http {
    client_max_body_size 10M;
    include mime.types;

    upstream authenticator {
        server authenticator-service:8090;
    }

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-store, must-revalidate";
        }

        location /uploads/ {
            alias /shared/openBanking/uploads/;
            valid_referers none blocked localhost:4200;
            if ($invalid_referer) {
                return 403;
            }
            add_header Cache-Control "no-store, must-revalidate";
        }

        location /uploads/client/ {
            alias /shared/openBanking/uploads/client/;
            autoindex off;
            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/fiche_de_paix/ {
            alias /shared/openBanking/uploads/fiche_de_paix/;
            autoindex off;
            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/pdf_contrats/ {
            alias /shared/openBanking/uploads/pdf_contrats/;
            autoindex off;
            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/archives_admin/ {
            alias /shared/openBanking/uploads/archives_admin/;
            autoindex off;
            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/website/ {
            alias /shared/openBanking/uploads/website/;
            autoindex off;
            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /authenticator/ {
            proxy_pass http://authenticator/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Removed the HTTPS redirect server block
}
