worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    limit_req_zone $binary_remote_addr zone=req_limit_api:10m rate=10r/s;

    limit_req_zone $binary_remote_addr zone=req_limit_uploads:10m rate=25r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;
    client_max_body_size 10M; 
    include mime.types;
    

    client_max_body_size 10M;
   
    default_type application/octet-stream;

    proxy_connect_timeout 1s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;
    send_timeout 30s;

    proxy_intercept_errors on;

    add_header Cache-Control "no-store, must-revalidate";

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 502 503 504 /custom_50x.html;
        error_page 404 /custom_404.html;

        location = /custom_50x.html {
            root /usr/share/nginx/html;
            internal;
        }

        location = /custom_404.html {
            root /usr/share/nginx/html;
            internal;
        }

        # Reverse proxies

       
       
        # Secure uploads

        location /uploads/ {
            alias /shared/openBanking/uploads/;
            valid_referers none blocked localhost:4200;
            if ($invalid_referer) {
                return 403;
            }
            add_header Cache-Control "no-store, must-revalidate";
        }

        location /uploads/client/ {
            alias /shared/openBanking/uploads/client/;
            autoindex off;

            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/fiche_de_paix/ {
            alias /shared/openBanking/uploads/fiche_de_paix/;
            autoindex off;

            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/pdf_contrats/ {
            alias /shared/openBanking/uploads/pdf_contrats/;
            autoindex off;

            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/archives_admin/ {
            alias /shared/openBanking/uploads/archives_admin/;
            autoindex off;

            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }

        location /uploads/website/ {
            alias /shared/openBanking/uploads/website/;
            autoindex off;

            location ~* \.(php|pl|py|sh|cgi|exe|bat)$ {
                deny all;
                return 403;
            }
        }
    }
}
